# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'sina框架' do

#source 'git@git.oschina.net:akuandev/Specs.git'
#source 'https://gitcafe.com/akuandev/Specs.git'

platform :ios, “8.3”

pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.0.8'
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking', '~> 2.6.3'
pod 'AliyunOSSiOS', '~> 2.3.0'

use_frameworks!

end

